name: Test App
on: push
jobs:
  test: 
    runs-on: windows-latest
    steps: 
      - name: Get code in repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Tasting application
        run: npm run test