name: test
on: workflow_dispatch
jobs: 
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo Hello Git Actions
      - name: Print new lines
        run: |
          echo First line!
          echo Second line!
